Remove support for GopherJS
fyne-io/tools pull request #4
Opened 2024-01-02 12:20 UTC by Jacalz

WIP PR for removing the support for using GopherJS.

2024-01-03 14:56 UTC, andydotxyz requested changes
Thanks for this, but can't this target be called "web" not "wasm"?
That way users won't have to change their behaviour from 2.4 unless they were previously specifying a subset of the web package?

2024-01-03 14:56 UTC, andydotxyz commented on cmd/fyne/internal/commands/package-wasm.go
> -func (p *Packager) packageWeb() error {
Shouldn't this wasm-only package format be called "web"?
The fact that it's a wasm binary internally should be considered an implementation detail I think.
So let's use the target name web, and use that for the folder as well.

Not sure we have to change this function name, but the file rename and folder here seemed like a good place to comment

2024-01-03 16:12 UTC, Jacalz commented
I was going to say that all other targets matched an operating system and that we ought to stick to wasm for consistency, but then I checked and wasm is the architecture and not the os. Technically we should do `js`, I guess, but maybe we can make `web` be an alias for that?

2024-01-03 16:13 UTC, Jacalz commented
(So yes, I agree but maybe we ought to use `js` instead of `web` as the os target)

2024-01-03 18:27 UTC, andydotxyz commented
I think it would be very confusing if we move to "js" and yet are removing the GopherJS support.
Also JS is a language and could imply that we are transpiling which is not what the web/WASM is doing.

I guess I don't see why we should move from the existing os=web which has been in place for over a year...

2024-01-03 23:14 UTC, Jacalz commented
Yeah, you are right. Using js would be more consistent with Go tooling but yeah (Go wasm builds actually have GOOS=js), it does give the wrong impression. I'll keep web and wasm around.

2024-02-19 07:42 UTC, Jacalz commented
I think it should be possible to merge this and pin the repo to the organization after that :)

2024-02-19 11:24 UTC, andydotxyz commented
Is it intended to keep the "js" os value present?

2024-02-19 14:22 UTC, Jacalz commented
Hmm. I forgot to remove hit but it is the actual GOOS for wasm so maybe we want to support it?

2024-02-19 14:41 UTC, andydotxyz approved these changes
OK, thanks - it seems like the right thing to do now.
We can always review if GopherJS gets a whole new lease of life

2024-02-19 18:01 UTC, merged

2024-02-19 18:01 UTC, Jacalz commented
You can pin the repo now :)

2024-02-20 08:35 UTC, andydotxyz commented
Done :)